SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 0) Ensure third identity exists: merchant service provider role/user.
INSERT INTO sys_role
(role_id, role_name, role_key, role_sort, data_scope, menu_check_strictly, dept_check_strictly, status, del_flag, create_by, create_time, remark)
VALUES
(3, '服务商家', 'merchant', 3, '2', 1, 1, '0', '0', 'admin', NOW(), '宠物服务商家角色')
ON DUPLICATE KEY UPDATE
role_name = VALUES(role_name),
role_key = VALUES(role_key),
status = '0',
del_flag = '0',
update_by = 'admin',
update_time = NOW();

INSERT INTO sys_user
(user_id, dept_id, user_name, nick_name, user_type, password, status, del_flag, create_by, create_time, remark)
VALUES
(
  3,
  100,
  'pet_merchant',
  'PetMerchant',
  '01',
  (SELECT password FROM (SELECT password FROM sys_user WHERE user_id = 1 LIMIT 1) t),
  '0',
  '0',
  'admin',
  NOW(),
  '服务商家测试账号'
)
ON DUPLICATE KEY UPDATE
nick_name = VALUES(nick_name),
user_type = VALUES(user_type),
status = '0',
del_flag = '0',
update_by = 'admin',
update_time = NOW();

INSERT IGNORE INTO sys_user_role (user_id, role_id) VALUES (3, 3);

-- Merchant users can access pet community features but not the audit center.
INSERT IGNORE INTO sys_role_menu(role_id, menu_id)
VALUES
(3, 2100), (3, 2101), (3, 2102), (3, 2103), (3, 2104), (3, 2105), (3, 2106),
(3, 2151), (3, 2152), (3, 2161), (3, 2162), (3, 2163);

-- 1) Ensure there is at least one non-admin user for social interactions.
INSERT INTO sys_user (user_id, dept_id, user_name, nick_name, user_type, password, status, del_flag, create_by, create_time)
VALUES (
  2,
  100,
  'pet_user2',
  'PetUser2',
  '00',
  (SELECT password FROM (SELECT password FROM sys_user WHERE user_id = 1 LIMIT 1) t),
  '0',
  '0',
  'admin',
  NOW()
)
ON DUPLICATE KEY UPDATE
nick_name = VALUES(nick_name),
status = '0',
del_flag = '0',
update_by = 'admin',
update_time = NOW();

INSERT IGNORE INTO sys_user_role (user_id, role_id) VALUES (2, 2);

-- 2) Rebuild business mock data for deterministic page testing.
TRUNCATE TABLE biz_activity_signup;
TRUNCATE TABLE biz_community_activity;
TRUNCATE TABLE biz_content_post;
TRUNCATE TABLE biz_social_friend;
TRUNCATE TABLE biz_social_match;
TRUNCATE TABLE biz_health_alert;
TRUNCATE TABLE biz_health_record;
TRUNCATE TABLE biz_pet_info;

-- 3) Pet profiles (owner 1: current admin user, owner 2: test user).
INSERT INTO biz_pet_info
(owner_user_id, pet_name, pet_gender, breed, birthday, age_month, weight_kg, avatar_url, social_tags, health_note, status, create_by, update_by)
VALUES
(1, 'Naitang', '1', 'Golden Retriever', '2023-04-15', 35, 26.50, '', 'golden,active,friendly,outdoor,frisbee', 'High energy and very social', '0', 'admin', 'admin'),
(1, 'Qiuqiu', '0', 'Corgi', '2022-12-10', 40, 12.40, '', 'corgi,active,playful,outdoor,walk', 'Loves short outdoor sessions', '0', 'admin', 'admin'),
(1, 'Doubao', '1', 'Ragdoll', '2024-01-20', 26, 4.90, '', 'cat,indoor,calm,friendly,quiet', 'Indoor cat with stable mood', '0', 'admin', 'admin'),
(2, 'Milo', '0', 'Labrador', '2023-02-01', 37, 24.80, '', 'labrador,active,friendly,outdoor,walk', 'Good with other dogs', '0', 'admin', 'admin'),
(2, 'Luna', '1', 'British Shorthair', '2023-06-18', 33, 5.20, '', 'cat,calm,indoor,friendly,quiet', 'Prefers calm environment', '0', 'admin', 'admin'),
(2, 'Coco', '1', 'Poodle', '2024-03-05', 24, 6.80, '', 'poodle,smart,active,trainable,playful', 'Quick learner and social', '0', 'admin', 'admin');

-- 4) Health records (mix of normal and abnormal).
INSERT INTO biz_health_record
(pet_id, record_date, weight_kg, food_intake_g, defecation_status, mental_status, symptom_desc, is_abnormal, create_by, update_by)
VALUES
(1, DATE_SUB(CURDATE(), INTERVAL 2 DAY), 26.40, 580, '0', '0', 'Normal condition', '0', 'admin', 'admin'),
(1, DATE_SUB(CURDATE(), INTERVAL 1 DAY), 26.10, 420, '1', '2', 'Loose stool and low energy', '1', 'admin', 'admin'),
(2, DATE_SUB(CURDATE(), INTERVAL 1 DAY), 12.30, 310, '0', '1', 'Slightly less active', '0', 'admin', 'admin'),
(3, DATE_SUB(CURDATE(), INTERVAL 1 DAY), 4.95, 180, '0', '0', 'Stable', '0', 'admin', 'admin'),
(4, DATE_SUB(CURDATE(), INTERVAL 1 DAY), 24.70, 560, '1', '0', 'Mild bowel issue', '1', 'admin', 'admin');

-- 5) Alerts generated by fixed rules.
INSERT INTO biz_health_alert
(pet_id, record_id, alert_type, alert_level, alert_content, alert_time, process_status, process_note, create_by, update_by)
SELECT r.pet_id,
       r.record_id,
       '4',
       CASE
         WHEN r.defecation_status = '1' AND r.mental_status = '2' THEN '3'
         ELSE '2'
       END,
       CASE
         WHEN r.defecation_status = '1' AND r.mental_status = '2' THEN 'Health Alert: abnormal defecation and low mental status detected, please seek offline check soon.'
         WHEN r.defecation_status = '1' THEN 'Health Alert: abnormal defecation detected, please continue observation.'
         ELSE 'Health Alert: low mental status detected, monitor appetite and activity.'
       END,
       NOW(),
       '0',
       '',
       'admin',
       'admin'
FROM biz_health_record r
WHERE r.is_abnormal = '1';

-- Mark one alert as processed for UI testing.
UPDATE biz_health_alert
SET process_status = '1', process_note = 'Checked by admin, continue monitoring.', update_by = 'admin', update_time = NOW()
ORDER BY alert_id ASC
LIMIT 1;

-- 6) Social interactions and friends (cross-user only).
INSERT INTO biz_social_match
(initiator_user_id, receiver_user_id, initiator_pet_id, receiver_pet_id, match_score, matched_tags, status, invite_type, invite_message, invite_time, event_time, event_location, response_time, create_by, update_by)
VALUES
(1, 2, 1, 4, 80, 'active,friendly,outdoor,walk', '2', 'Offline Meet', 'Let us walk together this weekend.', NOW(), DATE_ADD(NOW(), INTERVAL 2 DAY), 'Community Park', NOW(), 'admin', 'admin'),
(1, 2, 2, 6, 60, 'active,playful', '1', 'Pet Playdate', 'Want to arrange a short playdate?', NOW(), DATE_ADD(NOW(), INTERVAL 3 DAY), 'Pet Friendly Cafe', NULL, 'admin', 'admin'),
(2, 1, 5, 3, 70, 'cat,calm,indoor,friendly', '1', 'Experience Sharing', 'Can we exchange indoor cat care tips?', NOW(), DATE_ADD(NOW(), INTERVAL 1 DAY), 'Online Group', NULL, 'admin', 'admin');

INSERT INTO biz_social_friend
(user_id, friend_user_id, pet_id, friend_pet_id, source_match_id, status, create_by, update_by)
SELECT 1, 2, 1, 4, m.match_id, '0', 'admin', 'admin'
FROM biz_social_match m
WHERE m.initiator_pet_id = 1 AND m.receiver_pet_id = 4 AND m.status = '2'
LIMIT 1;

INSERT INTO biz_social_friend
(user_id, friend_user_id, pet_id, friend_pet_id, source_match_id, status, create_by, update_by)
SELECT 2, 1, 4, 1, m.match_id, '0', 'admin', 'admin'
FROM biz_social_match m
WHERE m.initiator_pet_id = 1 AND m.receiver_pet_id = 4 AND m.status = '2'
LIMIT 1;

-- 7) Content posts for publish/recommend/audit pages.
INSERT INTO biz_content_post
(creator_user_id, pet_id, content_type, title, summary, content_text, tags, media_url, status, review_status, review_by, review_time, review_note, create_by, update_by)
VALUES
(1, 1, '经验分享', 'Golden outdoor social tips', 'How to make dog social time safer outdoors.', 'Use gradual exposure and positive rewards for better social confidence.', 'golden,active,outdoor,adult', '', '0', '1', 'admin', NOW(), 'Approved', 'admin', 'admin'),
(1, 3, '日常动态', 'Indoor cat routine', 'A calm daily indoor routine for cats.', 'Short interactive play, steady feeding window, and quiet rest area.', 'cat,indoor,calm', '', '0', '0', '', NULL, '', 'admin', 'admin'),
(2, 4, '求助问答', 'Labrador appetite drop?', 'Slight appetite drop over two days.', 'Weight is stable but appetite dropped. Looking for experience.', 'labrador,active,adult,health', '', '0', '0', '', NULL, '', 'admin', 'admin');

-- 8) Community activities and signups.
INSERT INTO biz_community_activity
(creator_user_id, title, activity_type, location, start_time, end_time, pet_size_limit, max_participants, current_participants, status, review_status, review_by, review_time, review_note, description, create_by, update_by)
VALUES
(1, 'Weekend dog walk meetup', '线下遛宠', 'Central Community Park', DATE_ADD(NOW(), INTERVAL 2 DAY), DATE_ADD(NOW(), INTERVAL 2 DAY) + INTERVAL 2 HOUR, '不限', 20, 1, '1', '1', 'admin', NOW(), 'Approved', 'Light social walk and play.', 'admin', 'admin'),
(2, 'Indoor cat care sharing', '经验分享', 'Pet Friendly Cafe Room B', DATE_ADD(NOW(), INTERVAL 3 DAY), DATE_ADD(NOW(), INTERVAL 3 DAY) + INTERVAL 90 MINUTE, '不限', 12, 0, '0', '0', '', NULL, '', 'Share indoor cat care tips.', 'admin', 'admin');

INSERT INTO biz_activity_signup
(activity_id, user_id, pet_id, status, create_by, update_by)
SELECT a.activity_id, 1, 1, '0', 'admin', 'admin'
FROM biz_community_activity a
WHERE a.title = 'Weekend dog walk meetup'
LIMIT 1;

SET FOREIGN_KEY_CHECKS = 1;
